name: '#careerhacks'
favicon: null
layout_spectrum: 0.16956762201152742
typography_spectrum: 0.556793739553541
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3296576109714806
  lightness: 0.865760340820998
  saturation: 0.9996557915583253
  rhythmicContrast: 0.82844421826303
purpose: []
